### ISSUE TITLE
Why was BloodFix removed?

### ISSUE THREAD

**Issue by Rhikter937** [ermaccer/Manhunt.Fixer#2]
Had to do a fresh install, and suddenly the fixer was encountering an error again and again. Finally, I realized it wasn't something wrong with the fixer, it was because bloodfix.zip had been removed from the repository.

I'm pleased that I have the problem sorted out now, but I am curious: why was bloodfix removed from the most recent release?

**Comment by ermaccer** [comment]
MHP takes care of that way better as its done via code.
